##########someEmojis =   -_-,  ^_^  ,>_< , <3,  :'0  ,:'),  :'(  ,:'D  ,:'d  ,:'b  ,:'{  ,}:0  ,'}:'),  '}:'(  ,}:'D  ,}:'d  ,}:'b , }:'{  ,{:'0 , {:')  ,{:'(,  {:'D  ,{:'d,  {:'b,  {:'{,  (❁´◡`❁)   , (●'◡'●),╰( *°▽°*)╯, (*/ω＼*)  ,(^///^) ,ಥ_ಥ,( ┬┬﹏┬┬),ᓚᘏᗢ,ಠ_ಠ,(•_•),(☞ﾟヮﾟ)☞,(⌐■_■),(⊙ˍ⊙),(。_。),≡(▔﹏▔)≡,{{{(>_<)}}},<(＿　＿)> ,🤣 ,😃 ,😄 ,😅 ,😆 ,😉 ,😊 ,😋 ,😎 ,😍 ,😘 ,🥰 ,😗 ,🤨 ,🤔 ,🤩 ,🤗 ,🙂 ,☺ ,😚 ,😙 ,😐 ,😑 ,😶 ,🙄 ,😏 ,😣 ,😥, 😮, 😛, 😌 ,😴 ,🥱 ,😫 ,😪 ,😯 ,🤐 ,~~>_<~~ ,┗( T﹏T )┛, ಥ_ಥ ,╰（‵□′）╯]:::::::;::
word1 = (input('First word:'))
word2 = (input('Second word:'))
word3 = (input('Third word:'))
word4 = (input('Fourth word:'))
word5 = (input('Fifth word:'))
word6 = (input('Sixth word:'))
word7 = (input('Seventh word:'))
word8 = (input('Eighth word:'))
word9 = (input('Nineth word:'))
word10 = (input('Ten th word:'))
print('1😁 ' + word1+ '!!!!!!!!!!')
print('2 ' + word2 + '!!!!!!!!!!💚')
print('3 ' + word3 + '!!!!!!!!!😛!')
print('4 ' + word4 + '🤐!!!!!!!!!!')
print('5 ' + word5 + '!!!!!🧨!!!!!')
print('6 ' + word6 + '🛒!!!!!!!!!!')
print('7 ' + word7 + '!!!!!!!!!🚀')
print('8 🕶' + word8 + '!!!!!!!!!!')
print('9 ' + word9 + '!!🎆!!!!!!!!')
print('10 ' + word10 + '!!!!!!!!!!')