
numAndWord = (input('Input a lot of numbers and some long sentences:'))
#print(numAndWord[0])
#print(numAndWord[1])
#print(numAndWord[2])
#print(numAndWord.__sizeof__())
for i in range(1):
    print('there are...')
    print(numAndWord.count('A') , 'As')
    print(numAndWord.count('B') , 'Bs')
    print(numAndWord.count('C') , 'Cs')
    print(numAndWord.count('D') , 'Ds')
    print(numAndWord.count('E') , 'Es')
    print(numAndWord.count('F') , 'Fs')
    print(numAndWord.count('G') , 'Gs')
    print(numAndWord.count('H') , 'Hs')
    print(numAndWord.count('I') , 'Is')
    print(numAndWord.count('J') , 'Js')
    print(numAndWord.count('K') , 'Ks')
    print(numAndWord.count('L') , 'Ls')
    print(numAndWord.count('M') , 'Ms')
    print(numAndWord.count('N') , 'Ns')
    print(numAndWord.count('O') , 'Os')
    print(numAndWord.count('P') , 'Ps')
    print(numAndWord.count('Q') , 'Qs')
    print(numAndWord.count('R') , 'Rs')
    print(numAndWord.count('S') , 'Ss')
    print(numAndWord.count('T') , 'Ts')
    print(numAndWord.count('U') , 'Us')
    print(numAndWord.count('V') , 'Vs')
    print(numAndWord.count('W') , 'Ws')
    print(numAndWord.count('X') , 'Xs')
    print(numAndWord.count('Y') , 'Ys')
    print(numAndWord.count('Z') , 'Zs')

    print(numAndWord.count('a') , 'as')
    print(numAndWord.count('b') , 'bs')
    print(numAndWord.count('c') , 'cs')
    print(numAndWord.count('d') , 'ds')
    print(numAndWord.count('e') , 'es')
    print(numAndWord.count('f') , 'fs')
    print(numAndWord.count('g') , 'gs')
    print(numAndWord.count('h') , 'hs')
    print(numAndWord.count('i') , 'is')
    print(numAndWord.count('j') , 'js')
    print(numAndWord.count('k') , 'ks')
    print(numAndWord.count('l') , 'ls')
    print(numAndWord.count('m') , 'ms')
    print(numAndWord.count('n') , 'ns')
    print(numAndWord.count('o') , 'os')
    print(numAndWord.count('p') , 'ps')
    print(numAndWord.count('q') , 'qs')
    print(numAndWord.count('r') , 'rs')
    print(numAndWord.count('s') , 'ss')
    print(numAndWord.count('t') , 'ts')
    print(numAndWord.count('u') , 'us')
    print(numAndWord.count('v') , 'vs')
    print(numAndWord.count('w') , 'ws')
    print(numAndWord.count('x') , 'xs')
    print(numAndWord.count('y') , 'ys')
    print(numAndWord.count('z') , 'zs')
    print(numAndWord.count('1'), '1s')
    print(numAndWord.count('2'), '2s')
    print(numAndWord.count('3'), '3s')
    print(numAndWord.count('4'), '4s')
    print(numAndWord.count('5'), '5s')
    print(numAndWord.count('6'), '6s')
    print(numAndWord.count('7'), '7s')
    print(numAndWord.count('8'), '8s')
    print(numAndWord.count('9'), '9s')
    print(numAndWord.count('0'), '0s')
print('There are' , numAndWord.__len__() , 'letters/numbers in total.')
# numAndWord  = (input())
# print sorted(x)
# print sorted(x)
# print(numAndWord)
#
# numAndWord = (input('input some letters and numbers:'))
# x = [numAndWord]
# x.sorted()
# sorted({numAndWord})
# print('Sorted list:[',numAndWord, ']')VGAOLIRJD



