# how can you make something that can make multiple similar things (objects)?
# how do you print their values?
print('Enter the name of the first robot: Enter the age for the first robot:')
print('Enter the name of the second robot: Enter the age for the second robot:')
name1 = (input())
age1 = int(input())
name2 = (input())
age2 = int(input())
print('Metal robot ' + name1 + ': ' + str(age1) + ' years old')
print('Metal robot ' + name2 + ': ' + str(age2) + ' years old')
print('Metal robot Fred : 30 years old:')
print('Metal robot Bob: 20 years old')
print('Metal robot Rob: 38 years old')
print('Metal robot Boo: 19 years old')
print('Metal robot Desmond: 1 years old')
print('Metal robot William: 10283 years old')
print('Metal robot Micheal: 1000000 years old')
print('Metal robot R2D2: 103 years old')
print('Metal robot C3PO: 0.12years old')
print('Metal robot Lucas: 0.0000001 years old')
