from __future__ import annotations

import os
from pathlib import Path

from ai_gen.ai_client import OpenAIChatScriptClient, OpenAIClientConfig
from ai_gen.paths import resolve_path
from config.config import settings


DEFAULT_INPUT_PATH = "temps/ai/check_ai_gen/example.txt"
DEFAULT_OUTPUT_PATH = "temps/ai/check_ai_gen/example_review.txt"


def evaluate_example(
	input_path: str | Path = DEFAULT_INPUT_PATH,
	output_path: str | Path = DEFAULT_OUTPUT_PATH,
) -> Path:
	"""Ask the configured model to review output created by get_ai_completion."""

	api_key = os.getenv("OPENAI_API_KEY", "").strip()
	if not api_key:
		raise RuntimeError("OPENAI_API_KEY is required to run this example.")

	generated_path = resolve_path(input_path)
	if not generated_path.is_file():
		raise FileNotFoundError(
			f"Generated output was not found at {generated_path}. "
			"Run get_ai_completion first."
		)

	prompt_template = Path(__file__).with_name("check_ai_gen.md").read_text(encoding="utf-8")
	evaluation_prompt = prompt_template.replace(
		"{user_request}",
		"Write one short, useful tip for making automated tests reliable.",
	).replace(
		"{generated_response}",
		generated_path.read_text(encoding="utf-8"),
	).replace(
		"{available_context}",
		"The response was generated by get_ai_completion.py using the configured AI client.",
	)

	client = OpenAIChatScriptClient(
		OpenAIClientConfig(
			api_key=api_key,
			model=settings.ai_generation.model,
			base_url=settings.ai_generation.base_url,
		)
	)
	review = client.generate(
		system_prompt="You evaluate AI-generated content carefully and follow the requested output format.",
		user_prompt=evaluation_prompt,
	)

	destination = resolve_path(output_path)
	destination.parent.mkdir(parents=True, exist_ok=True)
	destination.write_text(review + "\n", encoding="utf-8")
	return destination


if __name__ == "__main__":
	print(f"Saved AI review to: {evaluate_example()}")
