from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

import yaml

from ai_stock.report.ai_report_agent import AIReportAgent, PredictionOutcome
from ai_stock.stock_data.ai_stock_data_agent import AIStockDataAgent
from ai_stock.stock_news.ai_stock_news_agent import AIStockNewsAgent


Predictor = Callable[[Dict[str, Any]], Dict[str, Any]]


@dataclass
class StrategyDefinition:
    name: str
    display_name: str
    description: str
    default_priority: int
    default_active: bool
    instructions: str


class AICoordinatorAgent:
    """Coordinates data/news/report sub-agents for stock up/down prediction."""

    def __init__(
        self,
        data_agent: Optional[AIStockDataAgent] = None,
        news_agent: Optional[AIStockNewsAgent] = None,
        report_agent: Optional[AIReportAgent] = None,
        predictor: Optional[Predictor] = None,
        strategies_dir: Optional[Path] = None,
    ) -> None:
        self.data_agent = data_agent or AIStockDataAgent()
        self.news_agent = news_agent or AIStockNewsAgent()
        self.report_agent = report_agent or AIReportAgent()
        self.predictor = predictor
        self.strategies_dir = strategies_dir or (Path(__file__).resolve().parents[1] / "strategies")

    def analyze(
        self,
        symbol: str,
        market: str = "cn",
        strategy_names: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        stock_data_context = self.data_agent.collect_context(symbol=symbol, market=market).to_dict()
        stock_news_context = self.news_agent.collect_context(symbol=symbol, market=market).to_dict()
        strategies = self._resolve_strategies(strategy_names)

        payload = {
            "symbol": symbol,
            "market": market,
            "stock_data": stock_data_context,
            "stock_news": stock_news_context,
            "strategies": [self._strategy_to_payload(item) for item in strategies],
        }

        prediction = self._predict(payload)

        return self.report_agent.build_report(
            symbol=symbol,
            market=market,
            prediction=prediction,
            strategy_names=[item.name for item in strategies],
            stock_data=stock_data_context,
            stock_news=stock_news_context,
        )

    def _predict(self, payload: Dict[str, Any]) -> PredictionOutcome:
        if self.predictor is not None:
            result = self.predictor(payload)
            return PredictionOutcome(
                direction=str(result.get("direction", "sideways")),
                confidence=float(result.get("confidence", 0.5)),
                reason=str(result.get("reason", "prediction generated by custom predictor")),
            )

        return self._baseline_prediction(payload)

    @staticmethod
    def _strategy_to_payload(strategy: StrategyDefinition) -> Dict[str, Any]:
        return {
            "name": strategy.name,
            "display_name": strategy.display_name,
            "description": strategy.description,
            "default_priority": strategy.default_priority,
            "instructions": strategy.instructions,
        }

    def _baseline_prediction(self, payload: Dict[str, Any]) -> PredictionOutcome:
        stock_data = payload.get("stock_data", {})
        stock_news = payload.get("stock_news", {})

        history = stock_data.get("history", [])
        news_sentiment = int(stock_news.get("sentiment_score", 0))

        trend_score = 0
        if len(history) >= 2:
            first_close = self._as_float(history[0].get("close"))
            last_close = self._as_float(history[-1].get("close"))
            if first_close is not None and last_close is not None and first_close > 0:
                change = (last_close - first_close) / first_close
                if change > 0.02:
                    trend_score += 1
                elif change < -0.02:
                    trend_score -= 1

        total_score = trend_score + news_sentiment

        if total_score > 0:
            direction = "up"
        elif total_score < 0:
            direction = "down"
        else:
            direction = "sideways"

        confidence = min(0.95, 0.5 + min(abs(total_score), 10) * 0.04)
        reason = (
            f"baseline model used trend_score={trend_score}, "
            f"news_sentiment={news_sentiment}, total_score={total_score}"
        )

        return PredictionOutcome(direction=direction, confidence=confidence, reason=reason)

    @staticmethod
    def _as_float(value: Any) -> Optional[float]:
        try:
            return float(value)
        except (TypeError, ValueError):
            return None

    def _resolve_strategies(self, selected_names: Optional[List[str]]) -> List[StrategyDefinition]:
        all_strategies = self._load_strategies()
        if not all_strategies:
            return []

        if selected_names:
            selected = set(selected_names)
            filtered = [item for item in all_strategies if item.name in selected]
            if filtered:
                return sorted(filtered, key=lambda item: item.default_priority)

        active = [item for item in all_strategies if item.default_active]
        if not active:
            active = all_strategies

        return sorted(active, key=lambda item: item.default_priority)

    def _load_strategies(self) -> List[StrategyDefinition]:
        if not self.strategies_dir.exists():
            return []

        strategy_files = sorted(self.strategies_dir.glob("*.yaml"))
        definitions: List[StrategyDefinition] = []

        for path in strategy_files:
            raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
            definitions.append(
                StrategyDefinition(
                    name=str(raw.get("name", path.stem)),
                    display_name=str(raw.get("display_name", raw.get("name", path.stem))),
                    description=str(raw.get("description", "")),
                    default_priority=int(raw.get("default_priority", 999)),
                    default_active=bool(raw.get("default_active", True)),
                    instructions=str(raw.get("instructions", "")),
                )
            )

        return definitions
